#
FROM ubuntu:20.04

# Install 'steam locomotive'
RUN apt-get update -y
RUN apt-get install -y sl

# Name the port
ENV PORT=8080

# command
CMD ["echo", "Hello there."]

# docker build -t echo .
# docker run echo
